Correctly honor file renames
The previous sed rule couldn't work, at least with the current error
file formats like:

    Error: PYLINT_WARNING:
    tests/test_cli.py:6: W4901[deprecated-module]: Deprecated module 'pipes'

I suppose the error format got changed when we started using the
vcs-diff-lint-csdiff-* wrappers.  Anyway, now we simply replace the
filename starting from the beginning of the line.